# Generated by Django 5.1.1 on 2025-03-09 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cedula",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("state", models.BooleanField(default=True)),
                (
                    "id_cedula",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[("C", "CEDULA"), ("R", "RUC")], max_length=75
                    ),
                ),
                ("fullName", models.CharField(max_length=255)),
                ("nacionalidad", models.CharField(max_length=50)),
                ("condicionCedulado", models.CharField(max_length=100)),
                ("esDiscapacitado", models.BooleanField(default=False)),
                ("fechaNacimiento", models.CharField(max_length=10)),
                ("edad", models.IntegerField(default=0)),
                ("esTerceraEdad", models.BooleanField(default=False)),
                (
                    "nombreMadre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "nombrePadre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("numeroCasa", models.CharField(blank=True, max_length=50, null=True)),
                ("profesion", models.CharField(blank=True, max_length=100, null=True)),
                ("sexo", models.CharField(blank=True, max_length=20, null=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lugarNacimiento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("codigoError", models.CharField(blank=True, max_length=20, null=True)),
                ("conyuge", models.CharField(blank=True, max_length=255, null=True)),
                ("domicilio", models.CharField(blank=True, max_length=255, null=True)),
                ("error", models.CharField(blank=True, max_length=255, null=True)),
                ("estadoCivil", models.CharField(blank=True, max_length=50, null=True)),
                ("genero", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "instruccion",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lugarInscripcionGenero",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fechaCedulacion",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fechaInscripcionDefuncion",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "fechaInscripcionGenero",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fechaLimitRefetch", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
