# Generated by Django 5.1.1 on 2025-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citizen", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cedula",
            name="tipo_identificacion",
            field=models.CharField(
                choices=[
                    ("CEDULA", "CEDULA"),
                    ("PASAPORTE", "PASAPORTE"),
                    ("RUC", "RUC"),
                ],
                max_length=75,
            ),
        ),
    ]
