# Generated by Django 5.1.1 on 2025-03-07 02:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultaBuro",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("state", models.BooleanField(default=True)),
                (
                    "id_consulta_buro",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identificacion", models.CharField(max_length=20)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[("C", "CEDULA"), ("R", "RUC")], max_length=75
                    ),
                ),
                (
                    "response_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("schema_name", models.CharField(max_length=200)),
                ("usuario_uuid", models.UUIDField()),
                ("empresa_uuid", models.UUIDField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
