# Generated by Django 5.1.1 on 2025-03-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultaburo",
            name="raw_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
