# Generated by Django 5.1.1 on 2025-03-07 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buro", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultaburo",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
