TIPO_IDENTIFICACION_EQUIFAX_CHOICES = (
    ('C', 'CEDULA'),
    ('R', 'RUC'),
)

TIPO_IDENTIFICACION_REGISTRO_CIVIL_CHOICES = (
    ('CEDULA', 'CEDULA'),
    ('PASAPORTE', 'PASAPORTE'),
    ('RUC', 'RUC'),
)
